equilibre_pro_tendance:
  LONDON_BRK: 0.1
  MEAN_REV: 0.1
  SMC: 0.3
  TREND: 0.35
  VOL_BRK: 0.15
agressif_chasseur_breakout:
  LONDON_BRK: 0.2
  MEAN_REV: 0.05
  SMC: 0.2
  TREND: 0.15
  VOL_BRK: 0.4
conservateur_suiveur_tendance:
  LONDON_BRK: 0.05
  MEAN_REV: 0.05
  SMC: 0.3
  TREND: 0.5
  VOL_BRK: 0.1
custom:
  TREND: 0.2
  SMC: 0.2
  MEAN_REV: 0.2
  VOL_BRK: 0.2
  LONDON_BRK: 0.2
