equilibre_pro_tendance:
  TREND: 0.35
  SMC: 0.3
  MEAN_REV: 0.1
  VOL_BRK: 0.15
  LONDON_BRK: 0.1
agressif_chasseur_breakout:
  TREND: 0.15
  SMC: 0.2
  MEAN_REV: 0.05
  VOL_BRK: 0.4
  LONDON_BRK: 0.2
conservateur_suiveur_tendance:
  TREND: 0.5
  SMC: 0.3
  MEAN_REV: 0.05
  VOL_BRK: 0.1
  LONDON_BRK: 0.05
custom:
  TREND: 0.2
  SMC: 0.2
  MEAN_REV: 0.2
  VOL_BRK: 0.2
  LONDON_BRK: 0.2
