equilibre_pro_tendance:
  INBALANCE: 0.15
  LONDON_BRK: 0.1
  MEAN_REV: 0.1
  SMC: 0.25
  TREND: 0.3
  VOL_BRK: 0.1
agressif_chasseur_breakout:
  TREND: 0.1
  SMC: 0.15
  MEAN_REV: 0.05
  VOL_BRK: 0.35
  LONDON_BRK: 0.15
  INBALANCE: 0.2
conservateur_suiveur_tendance:
  TREND: 0.45
  SMC: 0.25
  MEAN_REV: 0.05
  VOL_BRK: 0.05
  LONDON_BRK: 0.05
  INBALANCE: 0.15
custom:
  TREND: 0.15
  SMC: 0.15
  MEAN_REV: 0.15
  VOL_BRK: 0.15
  LONDON_BRK: 0.15
  INBALANCE: 0.25
